services:
  baseDatos:
    image: postgres:12.16-bookworm
    container_name: BaseApp
    hostname: Datos
    environment:
      POSTGRES_USER: Jodier
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    volumes:
      - ./baseDatos:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      red-Jodier:
        ipv4_address: 8.20.0.3
        
  pgadmin:
    image: dpage/pgadmin4:9.0.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      red-Jodier:
        ipv4_address: 8.20.0.4

  front:
    image: node:lts-bookworm
    container_name:  FrontApp 
    hostname: Practica
    # ports:
    #   - "3005:3000"
    command: "tail -f /dev/null"
    volumes:
      - ./front/next-app/chat:/app
    working_dir: /app
    networks:
      red-Jodier:
        ipv4_address: 8.20.0.2
  back:
    image: node:lts-bookworm
    container_name: BackApp
    hostname: Servidor
    # ports:
    #   - "3006:3000"
    command: "tail -f /dev/null"
    volumes:
      - ./back:/app
      - ./front/next-app/chat/prisma:/app/prisma:RO
      - ./front/next-app/chat/.env:/app/.env:RO
    working_dir: /app
    networks:
      red-Jodier:
        ipv4_address: 8.20.0.5
        




networks:
  red-Jodier:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 8.20.0.0/24
          gateway: 8.20.0.1

